//Code for reading BESS charge/discharge schedule as generated by external optimization python code
//It checks for presence of optimized_battery.txt file, once file is available, it starts execution and wakes up every minute at 59th second

#define BESS_SCHD_FILENAME "/usr/PVForecast+DAMAPI_LForecast/via JSON/optimized_battery.txt" //this is where python optimization code stores the file
#define INTERVAL 60  // Interval in seconds (5 seconds)

//syncrhonize start of execution to 59th second
void wait_until_next_minute() {
    time_t rawtime;
    struct tm *timeinfo;
    int seconds;
    time(&rawtime);
    timeinfo = localtime(&rawtime);
    seconds = timeinfo->tm_sec;
    // Calculate how many seconds to sleep until the next 59th second
    int sleep_seconds = (59 - seconds);
    sleep(sleep_seconds);
}

//sleep for 60sec
void wait_until_next_interval() {
    struct timespec ts;
    ts.tv_sec = 60;
    ts.tv_nsec = 0;
    nanosleep(&ts, NULL);
}

void* bess_optmize_thread (void* args) {

FILE *file;
int index = 0;
long offset;
//time_t current_time;

initial:
//Trigger at the next 59th second of the minute
wait_until_next_minute();

// Check if the file is present, wait if not
while ((file = fopen(BESS_SCHD_FILENAME, "r")) == NULL) {
    //printf("File not found. Waiting for the file to be available...\n");
	wait_until_next_interval();
}
goto read_bess_schedule;

while (1) {
    // Wait for the next interval
	wait_until_next_interval();

read_bess_schedule:
    // Read the element at the current index
    if (fscanf(file, "%d", &bess_opt_p) != 1) {
        perror("Error reading BESS Schedule file");
        fclose(file);
        goto initial;
    }

    if (usr_ctrl_mode==3)
    {
    	sem_post(&stchmgplc_tesla_psem);
    	// Get the current time
    	//time(&current_time);
    	//struct tm *local_time = localtime(&current_time);
    	printf("Current power: %d %d\n", index, bess_opt_p);

        // Print the current date and time
 /*       printf("Current Power %d %d: %02d-%02d-%04d %02d:%02d:%02d\n",
        	   index, bess_opt_p,
               local_time->tm_mday,
               local_time->tm_mon + 1,
               local_time->tm_year + 1900,
               local_time->tm_hour,
               local_time->tm_min,
               local_time->tm_sec);*/
    }

    if (index==1439) //1440 (0 to 1439) minutes in 24hours
    {
    	index = 0;
    	rewind(file);
    }

    else
    	index = index + 1;
}

fclose(file);
  return 0;
}
